---
- name: Create VLAN on NXOS network info
  #hosts: '{{target}}'
  hosts: switches
  connection: network_cli
  gather_facts: no

  tasks:
    - name: include vars #comment out this task if you want to use the Group Varable
      include_vars:
        file: vars/{{ projectname }}.yml


    - name: Configure VLAN ID on IOS
      ios_vlans:
        config:
          - vlan_id: "{{ item.vlan_id }}"
            name: "{{ project }}_{{ item.name }}"
            state: "{{ item.state }}"
        state: merged
      with_items: "{{ vlans }}"
      when: ansible_network_os == 'ios'

    - name: show VLAN from IOS
      ios_command:
        commands: show vlan brief
      register: show_vlan
      when: ansible_network_os == 'ios'
